### ISSUE TITLE
Can't pass token login

### ISSUE THREAD

**Issue by 2n4z0Xt** [Ar0basL4/Ur4BOT#1]
Hi, due to my lack of knowledge of Python, Im not able to fix this cuz I have literally no clue.
I was trying this Self-bot but, when I enter my token, there is no more message. (Waiting +10min)
The script seem to use more than 300mb when I start it and a bit after, he is using 2mb. Maybe the script is crashing? I have no error message or anything so this is weird.

Using Python 3.6.5

**Comment by Ar0basL4** [comment]
sorry, the selfbot works very well for me, I do not see where it can come from. I will try to optimize the self bot ...

**Comment by Ar0basL4** [comment]
> 
> 
> Hi, due to my lack of knowledge of Python, Im not able to fix this cuz I have literally no clue.
> I was trying this Self-bot but, when I enter my token, there is no more message. (Waiting +10min)
> The script seem to use more than 300mb when I start it and a bit after, he is using 2mb. Maybe the script is crashing? I have no error message or anything so this is weird.
> 
> Using Python 3.6.5

**Comment by Ar0basL4** [comment]
still sorry, I'll do my best and see how to fix that ...
thank you !
